project_id = "cleaning-duties"

[functions.notification-events]
enabled = true
verify_jwt = true
import_map = "./functions/notification-events/deno.json"
entrypoint = "./functions/notification-events/index.ts"

[functions.cleanup-archived-duties]
enabled = true
verify_jwt = true
entrypoint = "./functions/cleanup-archived-duties/index.ts"
